# Generated by Django 4.2.4 on 2023-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advs', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advs/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
